# Generated by Django 2.1.5 on 2019-01-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zhylbwg', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
