# Generated by Django 2.1.5 on 2020-03-10 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('zhylbwg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, '普通用户'), (2, 'VIP'), (3, 'SVIP')], null=True),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zhylbwg.Userinfo'),
        ),
        migrations.DeleteModel(
            name='UserInfoMessage',
        ),
    ]
