# Generated by Django 2.1.5 on 2020-03-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('zhylbwg', '0002_auto_20200303_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='userPwd',
            field=models.CharField(max_length=100),
        ),
    ]
