# Generated by Django 2.1.5 on 2019-01-09 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zhylbwg', '0003_hostgroup_hostinfromation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostinfromation',
            old_name='host_group',
            new_name='hostgroup',
        ),
    ]
