# Generated by Django 2.1.5 on 2019-01-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zhylbwg', '0004_auto_20190109_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfromation',
            name='host_ip',
            field=models.CharField(max_length=20),
        ),
    ]
